name: Java CI with Maven
on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    name: Java CI with Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create pull request - bugfix (conditional)
        if: startsWith(github.ref, 'refs/heads/bugfix')
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: bugfix
          template: .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
          get_diff: true

      - name: Create pull request - dependency (conditional)
        if: startsWith(github.ref, 'refs/heads/dependency')
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: dependency
          template: .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
          get_diff: true

      - name: Create pull request - documentation (conditional)
        if: startsWith(github.ref, 'refs/heads/documentation')
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: documentation
          template: .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
          get_diff: true

      - name: Create pull request - feature (conditional)
        if: startsWith(github.ref, 'refs/heads/feature')
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: feature
          template: .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
          get_diff: true

      - name: Create pull request - test (conditional)
        if: startsWith(github.ref, 'refs/heads/test')
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          reviewer: ${{ github.actor }}
          label: test
          template: .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
          draft: true
          get_diff: true

      - name: Create pull request - other (conditional)
        if: "!startsWith(github.ref, 'refs/heads/bugfix') && !startsWith(github.ref, 'refs/heads/dependabot') && !startsWith(github.ref, 'refs/heads/dependency') && !startsWith(github.ref, 'refs/heads/documentation')  && !startsWith(github.ref, 'refs/heads/feature') && !startsWith(github.ref, 'refs/heads/test')"
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          label: feature
          template: .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
          get_diff: true
